# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'KaKaoLink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KaKaoLink
pod 'KakaoSDKCommon', '~> 2.8.2'
  pod 'KakaoSDKAuth', '~> 2.8.2'
  pod 'KakaoSDKUser', '~> 2.8.2'
  pod 'KakaoSDKStory', '~> 2.8.2'
  pod 'KakaoSDKTalk', '~> 2.8.2'
  pod 'KakaoSDKLink', '~> 2.8.2'
  pod 'KakaoSDKNavi', '~> 2.8.2'
  pod 'KakaoSDKTemplate', '~> 2.8.2'
end
