# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleChatt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseFirestoreSwift'
pod 'Firebase/Firestore'

  # Pods for SimpleChatt


  target 'SimpleChattTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleChattUITests' do
    # Pods for testing
  end

end
