# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FSCalendar'
  # Pods for kb

  target 'kbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kbUITests' do
    # Pods for testing
  end

end
