# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KaKaoLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'KakaoSDKCommon'
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
pod 'AlamofireImage', '~> 4.1'
  # Pods for KaKaoLogin

end
